### ISSUE TITLE
OnClose animation on Adnroid is not smooth

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [dev-yakuza/react-native-image-modal#1]
OnClose animation on Adnroid is not smooth. When closing the modal, the close ending position in android device few pixel higher than real location. @dev-yakuza

**Comment by ManigandanRaamanathan** [comment]
@dev-yakuza also provide the option to modify the animation types. Like fade in or fade out. Based on react native animatable library. Thanks

**Comment by dev-yakuza** [comment]
@ManigandanRaamanathan 
thanks for feedback.
I checked bug and will fix soon.

and I'll think about animation types!

thnaks
