### ISSUE TITLE
Zoom under fingers

### ISSUE THREAD

**Issue by Keplyx** [dev-yakuza/react-native-image-modal#10]
Right now, the zoom works quite well but can feel counter intuitive when zooming at details not in the image's center.

**Desired behavior:**
When using pinch-to-zoom, zoom under fingers and allow image panning while holding with two fingers.

**Current behavior:**
When using pinch-to-zoom, the image zooms at the center of the screen, which is not necessarily where the user has its fingers.

**Comment by dev-yakuza** [comment]
Your suggestion is very reasonable! 👍 

I will improve it asap

thanks!

**Comment by dev-yakuza** [comment]
I tested it.

It is weird as you say. sometimes, pinch-to-zoom works well. I mean I can zoom to fingers center, not image center, but sometimes, pinch-to-zoom just zooms image center.... 🤔 

I will check it.

thanks for reporting!

**Comment by Razorholt** [comment]
Yup, same issue here. The pinch-to-zoom is not working well.
Other than that, I'm very pleased with your script. Thank you!
