### ISSUE TITLE
can't load a big image

### ISSUE THREAD

**Issue by stevesaygoodbuycom** [dev-yakuza/react-native-image-modal#12]
https://image.bada.io/files//crawling/2020/05/13/bhu/47147762_16fab2ff86b1307e9.jpg

size 963kb

can't load..

How can I do?

**Comment by dev-yakuza** [comment]
I think this library doesn't suit this kind of image.

![Simulator Screen Shot - iPhone 11 - 2020-05-21 at 09 26 19](https://user-images.githubusercontent.com/42969906/82510289-27bd7d80-9b45-11ea-83ca-6b85014a8338.png)

```js
<ImageModal
            isTranslucent={false}
            swipeToDismiss={false}
            resizeMode="contain"
            imageBackgroundColor="#000000"
            style={{
              width: imageWidth,
              height: 250,
            }}
            source={{
              uri:
                'https://image.bada.io/files//crawling/2020/05/13/bhu/47147762_16fab2ff86b1307e9.jpg',
            }}
          />
```

**Comment by stevesaygoodbuycom** [comment]
그럼 방법이 없는거네요? 긴 이미지는? 다른 줌 컴퍼넌트는 없을까요?

2020년 5월 21일 (목) 오전 9:27, JeongHean Kim <notifications@github.com>님이 작성:

**Comment by dev-yakuza** [comment]
네...이 라이브러리로는 조금 힘들거 같습니다....다른 라이브러리도 아마 원하시는 동작을 정확히 해줄지 모르겠네요.ㅠㅠ

https://github.com/ascoders/react-native-image-viewer

**Comment by stevesaygoodbuycom** [comment]
감사합니다 ~ 구글에서 근무하시나봐요.  저희 회사는 시애틀에 있습니다^^

2020년 5월 21일 (목) 오후 2:13, JeongHean Kim <notifications@github.com>님이 작성:

**Comment by dev-yakuza** [comment]
> 감사합니다 ~ 구글에서 근무하시나봐요. 저희 회사는 시애틀에 있습니다^^

아니요 저도 구글에서 일해보고 싶네요 😭 시애틀! 멋지시네요 👍 
죄송하지만, 여기는 react-native-image-modal에 관한 이슈를 다루는 부분이여서요.
혹시 라이브러리 이외에 궁금하신 부분이 있다면, dev.yakuza@gmail.com으로 연락주시면 감사하겠습니다.

감사합니다.

**Comment by stevesaygoodbuycom** [comment]
불러오네요~

근데 화질이 엄청 뿌연데... 왜 그럴까요?

2020년 5월 21일 (목) 오후 3:10, JeongHean Kim <notifications@github.com>님이 작성:

**Comment by stevesaygoodbuycom** [comment]
[image: image.png]

위가 imageModal
아래가  fastimage 입니다.

fastimage는 괜찮습니다...


2020년 5월 21일 (목) 오후 3:10, JeongHean Kim <notifications@github.com>님이 작성:

**Comment by stevesaygoodbuycom** [comment]
[image: image.png]

image를 FastImage로 변경하니 화질도 좋아졌네요. 감사합니다.

혹시 리액트 네이티브 전문가 재택근무로 구할 수 없을까요?

저희 앱 개발 중인데 튜닝해 줄...   속도가 많이 느려서요.. 특히 아이폰에서

2020년 5월 21일 (목) 오후 4:50, Steve Ryu <steve@saygoodbuy.com>님이 작성:

**Comment by dev-yakuza** [comment]
>[image: image.png]
>
>위가 imageModal
>아래가  fastimage 입니다.
>
>fastimage는 괜찮습니다...

사진이 보이지 않습니다 😭 사진을 다시 올려주시면 확인해 보겠습니다.
