### ISSUE TITLE
android imageModal does not cover statusBar

### ISSUE THREAD

**Issue by fukemy** [dev-yakuza/react-native-image-modal#123]
please help:
![Ảnh chụp Màn hình 2022-06-07 lúc 20 50 27](https://user-images.githubusercontent.com/8202437/172397150-46787fe7-8ac8-4dc1-8abf-0a6bbee1a39d.png)

**Comment by ROG3R-DEV** [comment]
same problem.

**Comment by fukemy** [comment]
I leaved this lib, too bad

**Comment by dev-yakuza** [comment]
The `isTranslucent` props may fix this.

- Example code: https://github.com/dev-yakuza/react-native-image-modal/blob/main/Develop/src/TranslucentStatusBar/index.tsx#L39

## Comparison

| Without isTranslucent | With isTranslucent |
| -- | -- |
| <video src="https://github.com/dev-yakuza/react-native-image-modal/assets/42969906/a7bff0b7-9fb1-4feb-a351-650b6e20a0a0" /> | <video src="https://github.com/dev-yakuza/react-native-image-modal/assets/42969906/cedf0fe9-46a1-408e-8181-3e20076c6220" /> |
