### ISSUE TITLE
`useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`

### ISSUE THREAD

**Issue by lucas123ho** [dev-yakuza/react-native-image-modal#13]
**Warning:** `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`

This warning was displayed when i updated expo to version 38.0.0

```
"expo": "^38.0.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz",
"react-native-image-modal": "^1.0.8",
```

It still works, but it would be nice to fix it. This parameter must have become required in the most recent version of react native.

**Comment by dev-yakuza** [comment]
Thanks for reporting!
I will check it asap!

**Comment by dev-yakuza** [comment]
@lucas123ho

I fixed it. Please update and use `v1.0.9`.

Thanks
