### ISSUE TITLE
Add modalRef open method

### ISSUE THREAD

**Issue by Zeigfreid** [dev-yakuza/react-native-image-modal#132]
I can't open programmatically, I see close function only, is it possible to add open function too?

**Comment by dev-yakuza** [comment]
Now, you can use the `ref` props to open and close the modal.

- Example: https://github.com/dev-yakuza/react-native-image-modal/blob/main/Develop/src/OpenCloseModalProgrammatically/index.tsx

| Open and close programmatically |
| -- |
| <video src="https://github.com/dev-yakuza/react-native-image-modal/assets/42969906/ae23698f-dfb0-44f1-b3b5-ee580e497250" /> |

**Comment by NhatBNPiconTech** [comment]
@dev-yakuza 
I got this error code when installing, can you help me
<img width="887" alt="Screenshot 2024-06-12 at 13 19 11" src="https://github.com/dev-yakuza/react-native-image-modal/assets/167288055/821ba06c-4246-4991-8edf-d2f181b77382">

**Comment by dev-yakuza** [comment]
@NhatBNPiconTech Sorry about that. I just fixed it.

- PR: https://github.com/dev-yakuza/react-native-image-modal/pull/272

Please try to use `3.0.2`.

**Comment by NhatBNPiconTech** [comment]
Thank you for that, I got it working again
