### ISSUE TITLE
Image not rendering?

### ISSUE THREAD

**Issue by dlogvin** [dev-yakuza/react-native-image-modal#17]
Hey, tried to use this lib, seemed exactly what I need... but for some reason it is not loading the image...

Here is my code:

```
<ImageModal
    resizeMode="contain"
    imageBackgroundColor="#000000"
    style={{
     height: 300, borderRadius: 15
}}
    source={{
        uri: converted,
    }}
/>
                                            <Image style={{
                                                    height: 300, borderRadius: 15
                                                }}
                                                source={{
                                                    uri: converted,
                                                }}/> 
```

Result: 

![Simulator Screen Shot - iPhone 11 - 2020-08-29 at 14 22 41](https://user-images.githubusercontent.com/62754263/91635730-795a8b80-ea03-11ea-9102-e9ab8ab61ae4.png)

**Comment by dlogvin** [comment]
Whoops, forgot to add the width. Is there any example that is non-typescript for setting the width automatically?

**Comment by dlogvin** [comment]
And, borderRadius is not working on this :(

**Comment by dev-yakuza** [comment]
> Whoops, forgot to add the width. Is there any example that is non-typescript for setting the width automatically?

Sorry. you should set the width to display the image. 😭

**Comment by dev-yakuza** [comment]
> And, borderRadius is not working on this :(

You can use `borderRadius`. just remove the `imageBackgroundColor` props.
