### ISSUE TITLE
i can't interative with custom renderFooter

### ISSUE THREAD

**Issue by josemi2201** [dev-yakuza/react-native-image-modal#172]
I'm trying to use `TouchableOpacity` of `react-native-gesture-handler` and the onPress function never work.

With `react-native` button works, but i need   the other component.

i'm using:

- React Native `0.68.1`
- react-native-image-modal `2.0.4`
- react-native-gesture-handler `2.4.1`

**Comment by dev-yakuza** [comment]
The following example code is working.

- https://github.com/dev-yakuza/react-native-image-modal/blob/main/Develop/src/CustomizeFooter/index.tsx

Please check this link.
