### ISSUE TITLE
Closing the full modal

### ISSUE THREAD

**Issue by KinanKazmi** [dev-yakuza/react-native-image-modal#21]
How do i programmatically close the full screen view without having to tap the X ?
`<ImageModal ref = {ref => this.previewBox = ref}...`
`this.previewBox.close()` or something ?

**Comment by dev-yakuza** [comment]
Hi @KinanKazmi 

First, Thanks for using this library.

Unfortunately, this library doesn't support closing the modal programmatically, now.

But I will try to add it!

**Comment by KinanKazmi** [comment]
Hey! Thanks for getting back so quick!
By far this is the best library that fills all my other requirements.
I know i just have to call `_close()` in the ImageDetail file somehow so i could make a local copy of this and modify it a little but unfortunately i dont know shit about typescripts, so I'm stuck for now. :(

**Comment by KinanKazmi** [comment]
This is my view requirement btw.
So i need to be able to close the full-screen view if the user clicks on any of the buttons i made on the bottom.

<img width="381" alt="Screenshot 2020-09-24 at 4 07 07 PM" src="https://user-images.githubusercontent.com/20215123/94137573-087e8600-fe80-11ea-91f8-c3b9daec3c81.png">

**Comment by dev-yakuza** [comment]
I am so sorry to hear that you stuck in typescript 😭 

And I got your point. it's very important that the user makes the custom close button.
So I'll add it asap 👍

**Comment by KinanKazmi** [comment]
Thanks :)
Waiting for the update.

**Comment by dev-yakuza** [comment]
I checked my source code, and I found that it actually has the customize feature.

https://github.com/dev-yakuza/react-native-image-modal/blob/9cd10bc8331de1b7624e34d61fd255ffd4e14e0c/src/index.tsx#L32-L33

I just forgot them. 😅 
But it doesn't have a feature that hides the default closing button, so I added and you can use it on v1.0.11

## Example

And I added the example about how to add the custom component with the close feature.

https://github.com/dev-yakuza/react-native-image-modal/blob/9cd10bc8331de1b7624e34d61fd255ffd4e14e0c/Example/App.tsx#L154-L176

Especially, here

https://github.com/dev-yakuza/react-native-image-modal/blob/9cd10bc8331de1b7624e34d61fd255ffd4e14e0c/Example/App.tsx#L163-L175

And you can use `onClose` to close the modal programmatically.

## Next

1. Update the react-native-image-modal to v1.0.11
1. Add the `hideCloseButton` option.
1. Add the custom component via `renderFooter` or `renderHeader`.
1. Use the `onClose` function to close the modal programmatically.

I hope this can solve your issue.

Thanks

**Comment by KinanKazmi** [comment]
It works! thanks a ton :)

by the way hideCloseButton doesn't hide the X.
But i want to keep it, so its not a problem for me
Cheers!

**Comment by dev-yakuza** [comment]
> by the way hideCloseButton doesn't hide the X.

Could you update the `react-native-image-modal` version(v1.0.11)?

> But i want to keep it, so its not a problem for me

Great! 👍  I will close this issue.

Thanks

**Comment by vrgimael** [comment]
Do you know if it would be difficult to simply add a ref so we could close the modal programatically? This would be even better as the modal might need to be closed according to other events, not only touches on the UI.

What I'm thinking is a glitch when you quickly flick through an image modal item on a flatlist and this triggers both momentum scroll and opening of the modal. As a result, the modal closes in the wrong position on the list (because it moved with momentum).

Any thoughts would be appreciated!

**Comment by dev-yakuza** [comment]
Hi @vrgimael ✋ 

Thanks for your opinions and for reporting the bug. 🙇‍♂️ 

I will add the `ref` and `disabled` props and I think it will solve the bug with scrolling.
You can disable and enable the opening model feature when the user scrolls the list. 🤔 

I will add them asap! 🚀 

Thanks

**Comment by dev-yakuza** [comment]
@vrgimael 

Now, you can use `Ref` to close the modal programmatically.

Please update the `react-native-image-modal` to `v1.0.12`.

1. import `useRef`
    https://github.com/dev-yakuza/react-native-image-modal/blob/b5257b1928d17c6456f38df53b9bc66fff2390ef/Example/App.tsx#L1
1. import `ImageDetail` type if you use typescript
    https://github.com/dev-yakuza/react-native-image-modal/blob/b5257b1928d17c6456f38df53b9bc66fff2390ef/Example/App.tsx#L12
1. define `Ref`
    https://github.com/dev-yakuza/react-native-image-modal/blob/b5257b1928d17c6456f38df53b9bc66fff2390ef/Example/App.tsx#L34
1. assign `Ref`
    https://github.com/dev-yakuza/react-native-image-modal/blob/b5257b1928d17c6456f38df53b9bc66fff2390ef/Example/App.tsx#L190
1. close the modal by using `Ref`
    https://github.com/dev-yakuza/react-native-image-modal/blob/b5257b1928d17c6456f38df53b9bc66fff2390ef/Example/App.tsx#L202

I hope you can solve the problem with this update!

Thanks

**Comment by artsztu27** [comment]
I add a custom close button but I can't close the image 

version  "react-native-image-modal": "^2.0.4"
```System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 41.46 MB / 16.00 GB
    Shell: 5.9 - /usr/local/bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/Downloads/GIT/app_frontend/node_modules/.bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: 2022.09.12.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 29, 31, 32, 33
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-33 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.1 => 0.70.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found```

**Comment by dev-yakuza** [comment]
Hi, @artsztu27 

Did you see the example?

https://github.com/dev-yakuza/react-native-image-modal/blob/318eec7d83c47630565a70341be0382638b6cbff/Example/App.tsx#L157-L180

Could you share your code?

Thanks
