### ISSUE TITLE
question about performance

### ISSUE THREAD

**Issue by fukemy** [dev-yakuza/react-native-image-modal#217]
Hi, do you ever test the performance, because i saw each image = (animatedview + modal), it's required more view hierarchy structure.

 I have large list of image, display as GridView, if I used `react-native-image-modal`, does it's took a lot of performance in my situation? Thanks

**Comment by dev-yakuza** [comment]
@fukemy I'm not sure that you still use this library.

I refactored the code to hide `Modal`.

- https://github.com/dev-yakuza/react-native-image-modal/blob/main/src/index.tsx#L170

So, may the performance is better than before.

I just close this issue. If you have still the performance issue, please let me know it.
