### ISSUE TITLE
Quickly flicking on a modal item on list causes momentum zoom glitch

### ISSUE THREAD

**Issue by vrgimael** [dev-yakuza/react-native-image-modal#24]
Basically, when you have a react-native-image-modal item on a flatlist, there is always the risk that the user would scroll so fast it's almost tapping, and this triggers both opening of the modal, and momentum scrolling of the list.

As a result the item animates back to the wrong position on the list because the list moved while it was fullscreen.

A potentially easy workaround could be exposing a modal close method so the modal could be dismissed when the list scrolls - ideally it wouldn't register both tap and scroll events at the same time (not sure why this happens)

**Comment by dev-yakuza** [comment]
Hi @vrgimael ✋ 

Could you try the new version(`v 1.0.12`) of `react-native-image-modal`? 🙏 

1. import `useRef`
    https://github.com/dev-yakuza/react-native-image-modal/blob/b5257b1928d17c6456f38df53b9bc66fff2390ef/Example/App.tsx#L1
1. import `ImageDetail` type if you use typescript
    https://github.com/dev-yakuza/react-native-image-modal/blob/b5257b1928d17c6456f38df53b9bc66fff2390ef/Example/App.tsx#L12
1. define `Ref`
    https://github.com/dev-yakuza/react-native-image-modal/blob/b5257b1928d17c6456f38df53b9bc66fff2390ef/Example/App.tsx#L34
1. assign `Ref`
    https://github.com/dev-yakuza/react-native-image-modal/blob/b5257b1928d17c6456f38df53b9bc66fff2390ef/Example/App.tsx#L190
1. close the modal by using `Ref`
    https://github.com/dev-yakuza/react-native-image-modal/blob/b5257b1928d17c6456f38df53b9bc66fff2390ef/Example/App.tsx#L202

**Comment by vrgimael** [comment]
Hi @dev-yakuza thanks for the quick response and sorry I didn't have the time to try this yet - will let you know as soon as I can
