### ISSUE TITLE
Bug when closing

### ISSUE THREAD

**Issue by MrNapcae** [dev-yakuza/react-native-image-modal#249]
When closing, the image overlaps other blocks from the top and bottom. How can I fix this behavior? I have attached a video.

https://github.com/dev-yakuza/react-native-image-modal/assets/42024544/84ab183f-2ecd-4c4e-bfea-e70deee29196

**Comment by dev-yakuza** [comment]
@MrNapcae Could you give the sample code for this issue?

**Comment by MrNapcae** [comment]
> @MrNapcaeНе могли бы вы дать пример кода для этой проблемы?

[Example сode RN](https://codesandbox.io/p/sandbox/loving-frog-79yq2u?file=%2Fsrc%2Findex.js%3A1%2C1-14%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwpf5xrk00063b6p4nrqxku0%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwpf5xrk00023b6p7tuzjfpz%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwpf5xrk00033b6pokhj96dk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwpf5xrk00053b6pc8hm5k4i%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwpf5xrk00023b6p7tuzjfpz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwpf5xrk00013b6psk9lmeck%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A14%252C%2522endColumn%2522%253A1%257D%255D%257D%255D%252C%2522id%2522%253A%2522clwpf5xrk00023b6p7tuzjfpz%2522%252C%2522activeTabId%2522%253A%2522clwpf5xrk00013b6psk9lmeck%2522%257D%252C%2522clwpf5xrk00053b6pc8hm5k4i%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwpf5xrk00043b6pg1h4a6jz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwpf5xrk00053b6pc8hm5k4i%2522%252C%2522activeTabId%2522%253A%2522clwpf5xrk00043b6pg1h4a6jz%2522%257D%252C%2522clwpf5xrk00033b6pokhj96dk%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwpf5xrk00033b6pokhj96dk%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by MrNapcae** [comment]
I looked through the codebase a bit and found out why this behavior is occurring: it's because Modal (react-native) is being used, and it positions itself above everything else, including FlatList. So, to achieve the same result, do we need to abandon Modal? Or are there other possible solutions? I would appreciate any help.

**Comment by dev-yakuza** [comment]
@MrNapcae Thanks for the information. I will take a look.

**Comment by dev-yakuza** [comment]
@MrNapcae

I'm almost close to fix the issue.


https://github.com/dev-yakuza/react-native-image-modal/assets/42969906/15e78bfc-1af6-41f1-85ca-c31d5792b0fa

I will refactor the code and release asap.

**Comment by MrNapcae** [comment]
> @MrNapcae
> 
> Я почти близок к решению проблемы.
> 
>  default.mov 
> Я проведу рефакторинг кода и выпущу его как можно скорее.

This is wonderful, many thanks!
