### ISSUE TITLE
MemoryLeak in flatList

### ISSUE THREAD

**Issue by tastafur** [dev-yakuza/react-native-image-modal#25]
Hello @dev-yakuza ,

I have a list of images implemented in your library to make posts and in this line I get a memory leak that ends up making the app work badly. I've been trying to fix it and haven't been able to.

https://github.com/dev-yakuza/react-native-image-modal/blob/develop/src/index.tsx#L149

![Captura de pantalla 2020-10-15 a las 13 57 49](https://user-images.githubusercontent.com/11853181/96120495-de543d00-0eee-11eb-8b94-0bd53dfef219.png)

**Comment by dev-yakuza** [comment]
Hi @tastafur 😃 

Thanks for your report. 🙇‍♂️  I will check it asap 🚀

**Comment by dev-yakuza** [comment]
@tastafur 

I removed the logic of it. Could you try `1.0.15`? 🙇‍♂️ 

If you still have the problem, please re-open the issue and let me know it.

Thanks
