### ISSUE TITLE
New release 3.0.1 ?

### ISSUE THREAD

**Issue by MrNapcae** [dev-yakuza/react-native-image-modal#259]
When can we expect a release on the issue? (https://github.com/dev-yakuza/react-native-image-modal/issues/249)
Current version 3.0.0...

**Comment by MrNapcae** [comment]
3.0.1?

**Comment by dev-yakuza** [comment]
@MrNapcae I just update it. Please try to use `3.0.1` and the `parentLayout` props.

You can see the example on the following link.

- https://github.com/dev-yakuza/react-native-image-modal/blob/main/Example/src/ParentLayout/index.tsx
