### ISSUE TITLE
Image orientation

### ISSUE THREAD

**Issue by deepak9705** [dev-yakuza/react-native-image-modal#26]
Image opened in potrait mode does not change to landscape when device rotated.it is locked in potrait mode.

Current behaviour: image clicked in potrait mode take full screen.it remains in potrait even device is rotated.

Expected behaviour: image rotate with the device rotation.

**Comment by dev-yakuza** [comment]
Hi @deepak9705 ✋ 

I will check it asap 🚀

**Comment by deepak9705** [comment]
Please see the attached photos.

Photo in potrait mode
![16052531392446363974653038291196](https://user-images.githubusercontent.com/61225854/99041712-6cd0e280-25b1-11eb-939a-45612090e161.jpg)

Photo in landscape mode
![16052531587061031555750681242399](https://user-images.githubusercontent.com/61225854/99041743-778b7780-25b1-11eb-8c9e-1e53a12bc992.jpg)

**Comment by dev-yakuza** [comment]
@deepak9705 

I fixed it. Could you try `1.0.15`? 🙏 

If you still have the problem, please re-open the issue.

Thanks
