### ISSUE TITLE
Image is blurred when styled with width 0 and height 0

### ISSUE THREAD

**Issue by NhatBNPiconTech** [dev-yakuza/react-native-image-modal#276]
when styling with
`style={{
                    width: 0,
                    height: 0
                  }}`
The first time I open it, the image will be blurry. The second time I open it, it will display normally. Please help me.
@dev-yakuza 

![Simulator Screenshot - iPhone 15 Pro - 2024-06-12 at 15 40 57](https://github.com/dev-yakuza/react-native-image-modal/assets/167288055/4dccb873-d9f3-4d0d-86ca-18a3c8ff1bd9)

**Comment by dev-yakuza** [comment]
@NhatBNPiconTech 

1. is it on Android or iOS?
2. Could you share the code?
3. Could you share the image?

**Comment by NhatBNPiconTech** [comment]
@dev-yakuza 
1. i have problem on  ios device
2. I want to hide images with a link. After clicking the link, the image modal will appear, so I did it the following way
 <img width="222" alt="Screenshot 2024-06-12 at 16 04 45" src="https://github.com/dev-yakuza/react-native-image-modal/assets/167288055/9f51650c-51d1-48a7-81fd-2759196399b2">
<img width="559" alt="Screenshot 2024-06-12 at 16 01
 44" src="https://github.com/dev-yakuza/react-native-image-modal/assets/167288055/ce1b6c3b-4bd5-4f8b-8f03-d9845e0c4556">

**Comment by dev-yakuza** [comment]
@NhatBNPiconTech So, Did you set `{ width: 0, height: 0 }` to `style={style}` in `<ImageModal />`?

I think you should correct image size to the `width` and `height`. I think you can use the `Image.getSize`. 

Could you check the following link and try to use `Image.getSize` and set the real size of the image to the style?

- https://github.com/dev-yakuza/react-native-image-modal/issues/73#issuecomment-1073410336

**Comment by dev-yakuza** [comment]
There is no response, so I close the issue.

If you have any problem, please reopen or make a new issue.

Thanks.
