### ISSUE TITLE
Big images problem

### ISSUE THREAD

**Issue by NazimMertBilgi** [dev-yakuza/react-native-image-modal#282]
Big images continue to show a black screen when clicked on.

My example image is 2 megabytes.
Is there a solution to this?

![Ekran Alıntısı](https://github.com/dev-yakuza/react-native-image-modal/assets/13032201/69b62c6b-7266-41c8-90fa-3402446e8562)

` <FlatList
                                                data={item.Fotograflar}
                                                horizontal={true}
                                                contentContainerStyle={{ gap: 10}}
                                                renderItem={(subItem) => {
                                                    return <ImageModal key={subItem.index}
                                                        resizeMode='contain'
                                                        imageBackgroundColor="#000000"
                                                        style={{
                                                            width: imageWidth,
                                                            height: 300,
                                                            borderRadius: 10,
                                                            zIndex: 1,
                                                            alignSelf: 'center',
                                                        }}
                                                        source={{ uri: subItem.item.replace("wwwroot", serverConstants.API_URL).replace(/\\/g, "/") }}
                                                    />
                                                }}
                                                keyExtractor={(subItem, index) => index.toString()}
                                            />`

**Comment by dev-yakuza** [comment]
@NazimMertBilgi Are other images(small images) shown well? Could you share the big image?

**Comment by dev-yakuza** [comment]
There is no response, so I close the issue.

If you have any problem, please reopen or make a new issue.

Thanks.
