### ISSUE TITLE
Cannot interact with renderHeader and renderFooter

### ISSUE THREAD

**Issue by nazacity** [dev-yakuza/react-native-image-modal#29]
I can't click on Tounchopacity
instead of clicking tounchopacity it is zoomed
        <ImageModal
          isTranslucent={false}
          resizeMode="contain"
          imageBackgroundColor={COLORS.background}
          overlayBackgroundColor="rgba(0,0,0,0.3)"
          source={item.picture_url}
          renderFooter={(onClose) => (
            <TouchableOpacity
              onPress={onClose}
              style={{
                backgroundColor: '#FFFFFF',
                height: 100,
                justifyContent: 'center',
                alignItems: 'center',
              }}>
              <Text>CloseButton</Text>
            </TouchableOpacity>
          )}
        />

**Comment by dev-yakuza** [comment]
Hi @nazacity 

There is an example of the `renderFooter`. And it works well on my local.

https://github.com/dev-yakuza/react-native-image-modal/blob/06bd0e24f5f6f6848f9c7ec9b4aeb116c184326a/Example/App.tsx#L156-L178

Could you check it on your local?

Thanks
