### ISSUE TITLE
is possible to fix border radius

### ISSUE THREAD

**Issue by nazacity** [dev-yakuza/react-native-image-modal#30]
https://drive.google.com/file/d/1SbUa-gSHwUzzOauQY89J5Xdr7QtDGG7a/view?usp=sharing

check this video

is possible to implement border radius more smoothly

**Comment by dev-yakuza** [comment]
Hi @nazacity 

I am not sure this change solves your issue. But if i add the `borderRadius` style in here, I can make it like below.

https://github.com/dev-yakuza/react-native-image-modal/blob/06bd0e24f5f6f6848f9c7ec9b4aeb116c184326a/src/ImageDetail/index.tsx#L693-L700

![ezgif com-gif-maker](https://user-images.githubusercontent.com/42969906/102079302-c9911880-3e4f-11eb-8a57-2b26727fee84.gif)

So I will add a `props` for the Image style in the Modal.

**Comment by dev-yakuza** [comment]
I updated the version. Could you try to use `v1.0.16`?

You can see the sample code in here.

https://github.com/dev-yakuza/react-native-image-modal/blob/24e9dab9217da29c135c961e172f03de05b0627b/Example/App.tsx#L247-L263

**Comment by itseramin** [comment]
Sorry for opening up this issue again, but my problem is i only want to have resizeMode 'cover' on my preview image while also having borderRadius on it but not when i click on it... so its resizeMode 'contain' and i have no borderRadius on it while opened. Any suggestions for that?
