### ISSUE TITLE
[Android] Malformed calls from JS: field sizes are different

### ISSUE THREAD

**Issue by MatiSera** [dev-yakuza/react-native-image-modal#31]
**RN version**: 0.63.2
**react-native-image-modal version**: ^1.0.16

Hi! I'm having this issue only in Android when I press in the image and try to open the modal
![image](https://user-images.githubusercontent.com/30613888/103101084-a0614c80-45f4-11eb-803c-25db721110d6.png)

And in console the error says:
![image](https://user-images.githubusercontent.com/30613888/103101097-afe09580-45f4-11eb-84ac-0a8b1c3258b5.png)

It's only happening on Android, in iOS works fine. Do you know why it could be? Thanks

**Comment by dev-yakuza** [comment]
Thanks for your reporting!

Could you try it again with `2.0.0` and `react-native-fast-image`?

https://github.com/dev-yakuza/react-native-image-modal#installation

**Comment by MatiSera** [comment]
I'm still having error when trying to open the image
![image](https://user-images.githubusercontent.com/30613888/103217738-1963eb00-48f8-11eb-82bf-1a7d26f3599b.png)

"react-native-image-modal": "2.0.0",
"react-native-fast-image": "^8.3.4"

This is what the error print in the terminal
![image](https://user-images.githubusercontent.com/30613888/103217824-4c0de380-48f8-11eb-8cc4-010fa58d75a3.png)

**Comment by dev-yakuza** [comment]
Do you use `hermes` on Android?

**Comment by alessiocancian** [comment]
This was fixed with #34

**Comment by dev-yakuza** [comment]
@alessiocancian Thanks 🙇‍♂️
