### ISSUE TITLE
about image style size and resizeMode

### ISSUE THREAD

**Issue by m0nk-lee** [dev-yakuza/react-native-image-modal#32]
I am going to make 40x40 image.

`<ImageModal style={{width: 40, height: 40}} />`

However, if do this, the quality of the picture becomes extremely poor in modal image like a forced extension of a 40x40 image.

- Can the original image size be 40x40 while maintaining the quality of the modal image?
- And can I set the `reziseMode` props of the original image and the modal image differently?

**Comment by dev-yakuza** [comment]
@asor7007 

Thanks for your reporting. 🙇‍♂️ 
I will check it asap. 🏃‍♂️

**Comment by nadavhalfon** [comment]
Was there any progress with the resizeMode dynamic value? 😁

**Comment by dev-yakuza** [comment]
Sorry

recently I am busy working... 😭 
I will try to see this issue this weekend.

**Comment by dev-yakuza** [comment]
@asor7007 @KushaanKapoor

You can use `modalImageResizeMode` on `v.2.0.3` of the library. 🚀 

https://user-images.githubusercontent.com/42969906/110889930-6ae61880-8332-11eb-8efe-4d37a1030590.mov

I hope this update helps you! 

https://github.com/dev-yakuza/react-native-image-modal/blob/62e93f53558a9d6e08c444dedb86177e03c225be/Example/App.tsx#L278-L319

**Comment by nadavhalfon** [comment]
Thank you!
