### ISSUE TITLE
Animated node with tag *** does not exists

### ISSUE THREAD

**Issue by dbotman** [dev-yakuza/react-native-image-modal#33]
On Android. 
iOS is working fine.

![Screenshot_1612110552](https://user-images.githubusercontent.com/61114720/106394047-c56a8b80-63fa-11eb-8acf-104261c20dd0.png)

react-native-image-modal: 2.0
react-native: 0.63
react-native-fast-image: 8.3.4

**Comment by dev-yakuza** [comment]
@dbotman 

Thanks for your reporting.

Could you give me more details?
I mean, Can you try to use the example of this library on the same device or simulator?
I am not sure which is the problem, I want you to test with the example in the library.

Thanks

**Comment by shriphani** [comment]
Facing this issue as well, running this using yarn android on a device, same config as @dbotman

**Comment by dbotman** [comment]
> @dbotman
> 
> Thanks for your reporting.
> 
> Could you give me more details?
> I mean, Can you try to use the example of this library on the same device or simulator?
> I am not sure which is the problem, I want you to test with the example in the library.
> 
> Thanks

I have it with a physical Android device and with the simulator. 
I can test it with the example later. But I see that @shriphani have the same issue.

**Comment by alessiocancian** [comment]
I have the same problem, I think it's related to #11  and #31 

I see errors like these in console:
```
Invariant Violation: [423,"RCTView",{"left":"<<NaN>>","top":"<<NaN>>","width":"<<NaN>>","height":"<<NaN>>"}] is not usable as a native method argument
```

```
Error:` Exception in HostFunction: Malformed calls from JS: field sizes are different.
[[18,18,18,2,18],[1,1,0,22,0],[[50],[51],[54,1,1612288055305,false],[56,0,1612288055308,false]],3184]
```

**Comment by alessiocancian** [comment]
I investigated a little more, found out that `measureInWindow` gets called with a value of undefined for all params (x, y, width and height), which results in NaN values sent to native code.

I fixed the crash by adding `onLayout` prop to the root View (see [https://github.com/facebook/react-native/issues/3282](url)).
I'm sending a PR right now.

**Comment by dbotman** [comment]
@alessiocancian I changed the file you've changed in the PR. But the issue still exists.

**Comment by alessiocancian** [comment]
> @alessiocancian I changed the file you've changed in the PR. But the issue still exists.

If you change it inside `node_modules` folder you need to change the js file inside `dist` folder because the library is compiled before publishing.

I temporary released the PR here if you want to try it: https://www.npmjs.com/package/react-native-image-modal-android-fix

**Comment by dbotman** [comment]
> > @alessiocancian I changed the file you've changed in the PR. But the issue still exists.
> 
> If you change it inside `node_modules` folder you need to change the js file inside `dist` folder because the library is compiled before publishing.
> 
> I temporary released the PR here if you want to try it: https://www.npmjs.com/package/react-native-image-modal-android-fix

@alessiocancian Fixed! Many thanks!
