### ISSUE TITLE
Expect custom baseline function to not return NaN libc++abi: terminating due to uncaught exception of type std::logic_error: Expect custom baseline function to not return NaN

### ISSUE THREAD

**Issue by griffinshuth** [dev-yakuza/react-native-image-modal#347]
when i try to use this i get this every time and the app crashes 
with this error 

Expect custom baseline function to not return NaN libc++abi: terminating due to uncaught exception of type std::logic_error: Expect custom baseline function to not return NaN

`  <ImageModal
    resizeMode='contain'
    modalImageResizeMode="contain"
style={{ width: windowWidth * .3, height: 200 }}
modalImageStyle={{ width: 800, height: 800 }}
  source={{uri: player?.profile_img != null ? playerImage : defaultProfileImage}}
  />`

**Comment by dev-yakuza** [comment]
Hi, @griffinshuth 

Does this occur only in this library?

I'm not sure this issue related https://github.com/facebook/react-native/issues/44406.

Could you check it?
