### ISSUE TITLE
Image width of 100%

### ISSUE THREAD

**Issue by Halfwai** [dev-yakuza/react-native-image-modal#353]
Thanks for the library, is there any way of setting the image width to 100% in the styling. It looks like I need to input a number of pixels, otherwise it default to a width of 0.

**Comment by dev-yakuza** [comment]
Hi, @Halfwai 

Thanks for using the library.

> Thanks for the library, is there any way of setting the image width to 100% in the styling. It looks like I need to input a number of pixels, otherwise it default to a width of 0.

For the animation, the image size is required.

I think you can get the image size by `Image.getSize` and set it to the library.

- Document: https://reactnative.dev/docs/image
- Stackoverflow: https://stackoverflow.com/questions/42170127/auto-scale-image-height-with-react-native
