### ISSUE TITLE
Custom Close Button Component

### ISSUE THREAD

**Issue by diaazzawi** [dev-yakuza/react-native-image-modal#36]
Is there a way to support custom component for the close button? It would be a nice feature.

**Comment by dev-yakuza** [comment]
Hi @diaazzawi 

Thanks for using this library.

You can use the custom header or footer component. See the example below.

https://github.com/dev-yakuza/react-native-image-modal/blob/fa282ace56b40429539942f3842eff4dda511eff/Example/App.tsx#L156-L178

You can hide the current close button with `hideCloseButton`, and add the custom component on the header or footer with `renderHeader` or `renderFooter`.

See the document on [here](https://github.com/dev-yakuza/react-native-image-modal#properties)

Thanks

**Comment by diaazzawi** [comment]
I apologize for missing this part in the documentation. Closing this issue...

Thank you!
