### ISSUE TITLE
Almost there

### ISSUE THREAD

**Issue by Razorholt** [dev-yakuza/react-native-image-modal#38]
First, thank you for this repo! A few things I've noticed:

1.- When you tap the image, it flickers first
2.- The pinch-to-zoom is still a bit buggy
3.- I'd like to be able to adjust the speed - and perhaps the easing - when you release the image

My goal is to try and replicate the behavior that you get on Apple News. So yes, you're almost there!!

**Comment by dev-yakuza** [comment]
Hi, @Razorholt 👋 

Thanks for your reporting and using this library.
I will fix the bug(1, 2) and add the option(3) when I have time! (You can contribute it if you have time :))
