### ISSUE TITLE
ResizeMode for Modal Image

### ISSUE THREAD

**Issue by KushaanKapoor** [dev-yakuza/react-native-image-modal#39]
Hey, I really like this library and I am currently using it in my react native application.

The thing I want to achieve is to have my Viewable Image with resizeMode cover while the Image Modal to have a different resizeMode, like contain.

is there any possible way to achieve this?

**Comment by dev-yakuza** [comment]
Hi @KushaanKapoor ✋ 

First, thanks for using this library.

I think this issue related to https://github.com/dev-yakuza/react-native-image-modal/issues/32

**Comment by KushaanKapoor** [comment]
I believe so, yes!

I'll be eagerly waiting for the next update for this library. thanks!
