### ISSUE TITLE
React import is missing it is throwing error in files \dist\components\OriginImage\index.js

### ISSUE THREAD

**Issue by hareesh7777** [dev-yakuza/react-native-image-modal#425]
ERROR  ReferenceError: Property 'React' doesn't exist

This error is located at:
 in OriginImage (at dist/index.js:50)
 
  ERROR  ReferenceError: Property 'React' doesn't exist

This error is located at:
    in ImageArea (at ImageDetail/index.js:129)

same in file \dist\components\ImageDetail\components\ImageArea\index.js

**Comment by dev-yakuza** [comment]
Could you give me more information? How do I make this error?

**Comment by dev-yakuza** [comment]
@hareesh7777 Could you give me more information? How do I make this error?

**Comment by hareesh7777** [comment]
![Screenshot_20241121_162227 1](https://github.com/user-attachments/assets/69697013-7233-4781-808b-e6ead23482f7)
i'm using ImageModal like below, whenever i navigate to the screen which is using ImageModal it is throwing error               
                
react native version is ^0.73.10
react-native-svg  version is ^15.9.0

```
<ImageModal
source={{uri: link to image}}
resizeMode="cover"
ref={imageRef}
modalImageResizeMode="contain"
swipeToDismiss={true}
/>
```
after adding React import it is working good

**Comment by hareesh7777** [comment]
![Screenshot_20241121_162227 1](https://github.com/user-attachments/assets/d54bf415-a86b-4004-acdb-e79bd8cb4f98)

**Comment by hareesh7777** [comment]
![Screenshot_20241121_162227 1](https://github.com/user-attachments/assets/0f95d128-6d25-4b32-a7c4-d6b19cf0180d)

**Comment by hareesh7777** [comment]
![Screenshot_20241121_162227 1](https://github.com/user-attachments/assets/7a0c6dd3-3dad-4e22-b550-ce7f7507d214)

**Comment by dev-yakuza** [comment]
@hareesh7777 

I fix the error on https://github.com/dev-yakuza/react-native-image-modal/pull/434.
And release it.

Could you try to update to `3.0.13` and let me know that it still occurs?

Thanks

**Comment by hareesh7777** [comment]
@dev-yakuza thanks 
it is fixed
