### ISSUE TITLE
Fast Image 버그로 인한 Issue

### ISSUE THREAD

**Issue by RyuWoong** [dev-yakuza/react-native-image-modal#54]
Fast Image View에 버그가 존재합니다.
따라서 해당 문제를 해결할 방법이 필요합니다.
관련 버그 :  https://github.com/DylanVann/react-native-fast-image/issues/623

**Comment by dev-yakuza** [comment]
@RyuWoong 
버그 리포팅 감사합니다.
현재 라이브러리를 사용하시면서 같은 문제가 발생하고 계신가요?

혹시

https://github.com/DylanVann/react-native-fast-image/issues/623#issuecomment-679906369

이걸로 해결이 가능하신가요?

**Comment by RyuWoong** [comment]
@dev-yakuza 
저의 무지로 인한 문제 같습니다. 이상없습니다.

**Comment by dev-yakuza** [comment]
@RyuWoong 
바쁘시겠지만, 혹시 어떤 부분 때문이였고, 어떻게 해결하셨는지 공유 가능하실까요?
다른 분들도 같은 문제를 겪으실 수 있을거 같아서요.
바쁘시겠지만 잘 부탁드립니다 🙇‍♂️
