### ISSUE TITLE
Image in modal is blur in Android

### ISSUE THREAD

**Issue by jagwingchoy** [dev-yakuza/react-native-image-modal#58]
## Description
Hi there! I am using this package inside my app project. The function is working perfectly inside iOS, while in Android the image is blurred inside the modal when I click the image and open it. Does anyone encounter this issue? How do you solve it? Appreciate any help or suggestion.

#### Working or not:
✅   iOS simulators
✅   iOS real devices
❌   Android emulators
❌   Android real devices

---

### Codes
    <ImageModal resizeMode="contain" source={{ uri: imageUrl }} style={{ height: 100, width: 100 }} />

### package.json
    ...
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-fast-image": "8.3.4",
    "react-native-image-modal": "2.0.3",
    ...

## The screenshot
![image](https://user-images.githubusercontent.com/58965922/125560808-0db7ca2a-17e3-41c2-b838-d0aabb42169e.png)

**Comment by dev-yakuza** [comment]
@jagwingchoy 
Is the image file perfectly the same? I mean, do you take a picture and save it and then show it via `react-native-image-modal`?

Basically, the `react-native-image-modal` just shows the image, so I guess the image is different between iOS and Android by other libraries(e.g. take a picture library can make low quality of the image).

**Comment by jagwingchoy** [comment]
Hi @dev-yakuza , the image is from network using same link, so basically should be identical.

The issue is happen only in `Android` with smaller size, i.e.:  

    ...style={{ height: 100, width: 100 }}

If I change using a larger size e.g. `height: 800, width: 800`, then Android will also show a normal non-blurred image.

**Comment by cylim** [comment]
@jagwingchoy Are you able to set the size dynamically when open the modal?

**Comment by datoonw13** [comment]
Any update?

**Comment by cylim** [comment]
My workaround is to set minWidth and minHeight, but it will affect the animation a bit.

```js 
const {width, height} = Dimensions.get('screen');
<ImageModal
          isTranslucent
          style={{width: 100, height: 100}}
          modalImageStyle={{minHeight: height, minWidth: width}}
          source={{
            uri: i.url,
            priority: FastImage.priority.high,
          }}
          resizeMode={FastImage.resizeMode.cover}
          modalImageResizeMode={FastImage.resizeMode.contain}
        />
```

Due to the modalImageStyle had hardcoded width and height to 100%, we can't change it, unless patching the package.

**Comment by jagwingchoy** [comment]
Hi @cylim,  
Thanks for your suggestion. I have tried to change the codes as you mentioned and create a patch to fix this issue.

```diff
diff --git a/node_modules/react-native-image-modal/dist/ImageDetail/index.js b/node_modules/react-native-image-modal/dist/ImageDetail/index.js
index e132b47..c94a3a7 100644
--- a/node_modules/react-native-image-modal/dist/ImageDetail/index.js
+++ b/node_modules/react-native-image-modal/dist/ImageDetail/index.js
@@ -576,8 +576,8 @@ var ImageDetail = (function (_super) {
           <FastImage resizeMode={resizeMode} style={[
             imageStyle,
             {
-                width: '100%',
-                height: '100%',
+                width: windowWidth,
+                height: windowHeight,
             },
         ]} source={source}/>
         </Animated.View>

```

@dev-yakuza Not sure if it is the correct fix,  
but I do hope you could help to fix the issue in the next release version, thanks.

**Comment by tonyneel** [comment]
This fixed the issue for me for the images when the modal is active. However the small image before the modal pops up is still blurry. Is there a way to fix that?
