### ISSUE TITLE
Can it do picture carousel

### ISSUE THREAD

**Issue by gbfriendship** [dev-yakuza/react-native-image-modal#6]
Very necessary

**Comment by dev-yakuza** [comment]
@gbfriendship 

When you click an image, and that image is full size.
And then, Do you want to swipe to show other pictures?

If you go to another picture by swipe and close the modal, do you want to close to original image?

Please let me know what you want

Thanks

**Comment by tastafur** [comment]
Hello
@dev-yakuza Must want something like what's done here https://github.com/ascoders/react-native-image-viewer

**Comment by dev-yakuza** [comment]
@tastafur 
Thanks for giving the opinion. I understand the point, but I want this repository to be simple.(Honestly, there are so many libraries like react-native-image-viewer... 😭)
