### ISSUE TITLE
Styling issue for model image

### ISSUE THREAD

**Issue by mak12** [dev-yakuza/react-native-image-modal#68]
Hi, first of all library is great and works smooth.
Now I cam across an issue in the scenario where origin image is round (has border radius) so model image opens complete and in square or rectangle form that's fine too, but when its closing with animation of square and when it reaches origin we see a jerk where model small size image is rectangle and then origin comes with border radius.
For the time being I applied borderRadius to modelImageStyle and it now closes with circle so removes that jerk but issue is that model image now has border radius, attaching ScreenShot for reference.
![Simulator Screen Shot - iPhone 8 - 2021-12-09 at 13 10 50](https://user-images.githubusercontent.com/30626811/145359118-3449de4a-ed7d-44d3-bfaa-439aac659179.png)

**Comment by mak12** [comment]
It would be great if we have any control or when closing model image adopts origin image styling.

**Comment by dev-yakuza** [comment]
@mak12 

Is it related to https://github.com/dev-yakuza/react-native-image-modal/issues/30#issuecomment-744408824? 🤔  Could you check it? 🙏

**Comment by mak12** [comment]
@dev-yakuza 

https://user-images.githubusercontent.com/30626811/145409415-8db32d79-aabd-46bb-82ea-05aa807f8bbb.mov

Please see this recording, and when its closing see the behaviour, when its changing from square to circle

**Comment by dev-yakuza** [comment]
@mak12 

Could you share your code about `<ImageModal />`?

**Comment by mak12** [comment]
@dev-yakuza 
` <ImageModal
                                    isRTL={isRTL()}
                                    resizeMode="cover"
                                    style={{
                                        alignSelf: 'center',
                                        width:(56),
                                        height:(56),
                                        borderRadius:(56),
                                        backgroundColor: colors.INPUT_BACKGROUND
                                    }}
                                    source={item.logo}
                                />`
                                                                
here is the code snippet
