### ISSUE TITLE
Multiple image slider

### ISSUE THREAD

**Issue by kinkin626** [dev-yakuza/react-native-image-modal#69]
The zoom functionality works flawlessly and much better compared to other image slider libraries available out there

Can you please add the functionality of multiple images

**Comment by dev-yakuza** [comment]
@kinkin626 Thanks for using this library.

I'm so sorry, But I don't have any plan to add the multiple-image slider.

Because I want to keep this simple.

If you want to use multiple images, I think you can use other libraries.

- https://github.com/jobtoday/react-native-image-viewing

**Comment by kinkin626** [comment]
Hey @dev-yakuza the library you suggested has double finger zoom issue, similarly other library has double tap issue, so I requested for multiple image support

**Comment by dev-yakuza** [comment]
I don't have any plan to add the multiple image slider, so I just close this issue.
