### ISSUE TITLE
Use auto height

### ISSUE THREAD

**Issue by dbotman** [dev-yakuza/react-native-image-modal#73]
Hello @dev-yakuza,

Is there an option or what is the best way to use auto height ?
We want to show the image at 100% width with height based on the image.

**Comment by dev-yakuza** [comment]
Hi, @dbotman ✋ 

> Is there an option or what is the best way to use auto height?

I'm sorry that this library doesn't support the auto height option. 😭 

I think you can make it with the `Image.getSize`.

- Document: https://reactnative.dev/docs/image
- Stackoverflow: https://stackoverflow.com/questions/42170127/auto-scale-image-height-with-react-native

**Comment by dbotman** [comment]
Hi @dev-yakuza,

Thanks for your answer.

Correct me if i'm wrong, when you use Image.getSize before loading the Image Modal then you download the picture twice.
I am already using this at the moment. I'm see a longer loading time of the pictures when using Image.GetSize before.
When i test with a fixed size the images loading faster.

**Comment by dev-yakuza** [comment]
> Hi @dev-yakuza,
> 
> Thanks for your answer.
> 
> Correct me if i'm wrong, when you use Image.getSize before loading the Image Modal then you download the picture twice. I am already using this at the moment. I'm see a longer loading time of the pictures when using Image.GetSize before. When i test with a fixed size the images loading faster.

Hi, @dbotman 

According to the [document](https://reactnative.dev/docs/image#getsize),

> In order to retrieve the image dimensions, the image may first need to be loaded or downloaded, after which it will be cached. This means that in principle you could use this method to preload images, however it is not optimized for that purpose, and may in future be implemented in a way that does not fully load/download the image data. A proper, supported way to preload images will be provided as a separate API.

To get the size, the image is downloaded, and if you want to prevent downloading the image multiple, you can preload the image.

So, I think you can preload the image by the [prefetch()](https://reactnative.dev/docs/image#prefetch) and then, get the size of the image, and display it with the size. Have you ever tried this one? 🤔
