### ISSUE TITLE
modalImageResizeMode not working

### ISSUE THREAD

**Issue by Hanafubuki** [dev-yakuza/react-native-image-modal#77]
Hi, I am trying to use modalImageResizeMode, but it doesn't work. It copies the behavior of resizeMode. I believe it's because I am using expo. Do you have any plans to fix it for expo? Thank you.
Here is my code
`<ImageModal
                                resizeMode="cover"
                                modalImageResizeMode="contain"
                                imageBackgroundColor="#000000"
                                style={{
                                width: width,
                                height: 250,
                                }}
                                source={{uri: file.item.path}}
                            />`

**Comment by dev-yakuza** [comment]
Hi, @Hanafubuki 

Have you ever checked the example code?

https://github.com/dev-yakuza/react-native-image-modal/blob/main/Example/App.tsx#L278-L319

https://user-images.githubusercontent.com/42969906/164380887-689fe84d-3fb0-4179-9003-3da5e6b49a91.mov

It looks fine 🤔

**Comment by thame** [comment]
If you're using the version that supports Expo it appears that this prop is not available. You can copy the changes from this commit if you'd like to add support.

https://github.com/dev-yakuza/react-native-image-modal/commit/defeeefeba2613711d0e0eb11dd594b488512937

**Comment by dev-yakuza** [comment]
The newest version of the library supports `Expo`, so you can use this props.
