### ISSUE TITLE
Animation problem on Expo

### ISSUE THREAD

**Issue by Keplyx** [dev-yakuza/react-native-image-modal#9]
I started using your lib and it works perfectly on bare react native.

Sadly, I need to use expo and I found a small bug: When closing the modal, the animation stops a few pixels below the starting point, freezes there a few milliseconds, and teleports to its original position.

See the following GIF:
![image-modal-bug](https://user-images.githubusercontent.com/23726131/78462583-e62b5d00-76d3-11ea-8482-1d8a7372a080.gif)

**Steps to reproduce:**
* Start a new expo project with `expo init`
* Copy the code from [the example](https://github.com/dev-yakuza/react-native-image-modal/blob/develop/Example/App.tsx) and paste it in your new project App.js (removing jsx related anotations if needed).
* Start the project on emulator or real device with `expo start`

The same code works perfectly on the same emulator when using only react native and not expo.

Hope you will be able to find a fix!

**Comment by dev-yakuza** [comment]
Sorry to reply too late.

I will check this library on Expo!
And I will fix it asap!

thanks!

**Comment by dev-yakuza** [comment]
@Keplyx 

I've checked and I think this is because of `translucent` in Expo

```
{
  "expo": {
    ...
    "androidStatusBar": {
      "translucent": false
    }
  }
}
```

If you set like above, you can solve this problem. I didn't find better solutions.

**Comment by dev-yakuza** [comment]
I added `isTranslucent` props for this issue.

You can see the example for Expo.

https://github.com/dev-yakuza/react-native-image-modal/blob/75139318cb6459db947d607fa38d520914bfab4c/ExampleWithExpo/App.tsx#L54-L76

I close this issue.

thanks

**Comment by Keplyx** [comment]
Thank you ! I tried your example and it works, but in my project, the isTranslucent prop does not change anything (and yes I updated the lib). Settings the status bar to not translucent in app.json fixes it as you said, but I cannot do that.

Maybe this is due to react navigation? I'll try to find more information on the issue.

**Comment by dev-yakuza** [comment]
Sorry to hear that 😭 

How about Expo version?
If you can share your project, please share it to find the problem together.

thanks.

**Comment by Keplyx** [comment]
The project I am working on is quite big, so I instead tried to reproduce the issue in a smaller project to try and find the source.

The problem lies with react navigation headers.

I took your example, installed `@react-navigation/native` and `@react-navigation/stack` (with all necessary dependencies), and rendered the screen inside a stack navigator. The view jumps whether I use `isTranslucent` or not. It is even worse if set, because the modal and the whole screen will jump as the status bar is shown again.

**Comment by Keplyx** [comment]
I ended up following [expo recommendations on handling the StatusBar](https://docs.expo.io/versions/latest/guides/configuring-statusbar/) with 3rd party libraries and it now works perfect!

I the end, I keep the bar translucent so that is matches the splash screen, then I use:

```javascript
StatusBar.setTranslucent(false);
StatusBar.setBackgroundColor(COLOR);
StatusBar.setBarStyle(STYLE, true);
```

To match the current dynamic theme

**Comment by dev-yakuza** [comment]
Cool! I am happy to hear that! ❤️ 

and thanks for sharing your solution. I hope your command helps someone!

thanks.
